"""empty message

Revision ID: 049408124505
Revises: 
Create Date: 2020-07-29 22:44:54.452836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049408124505'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('city', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'city')
    # ### end Alembic commands ###
