"""empty message

Revision ID: 87a875921b72
Revises: 049408124505
Create Date: 2020-07-29 22:45:54.593098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a875921b72'
down_revision = '049408124505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
