"""empty message

Revision ID: 8f2fa62ec487
Revises: 87a875921b72
Create Date: 2020-07-29 22:47:44.295246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2fa62ec487'
down_revision = '87a875921b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('city', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'city')
    # ### end Alembic commands ###
